name: tradex_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Network
  dio: ^5.4.0
  retrofit: ^4.0.3
  
  # UI Components
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # State Management
  provider: ^6.1.1
  
  # URL Launcher
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  injectable_generator: ^2.4.1
  
  # App Icons and Splash Screen
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6


flutter:
  generate: true


  uses-material-design: true


  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/font/NotoSansArabic-Thin.ttf
          weight: 100
        - asset: assets/font/NotoSansArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/font/NotoSansArabic-Light.ttf
          weight: 300
        - asset: assets/font/NotoSansArabic-Regular.ttf
          weight: 400
        - asset: assets/font/NotoSansArabic-Medium.ttf
          weight: 500
        - asset: assets/font/NotoSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/font/NotoSansArabic-Bold.ttf
          weight: 700
        - asset: assets/font/NotoSansArabic-ExtraBold.ttf
          weight: 800
        - asset: assets/font/NotoSansArabic-Black.ttf
          weight: 900
    - family: NotoSansArabicCondensed
      fonts:
        - asset: assets/font/NotoSansArabic_Condensed-Thin.ttf
          weight: 100
        - asset: assets/font/NotoSansArabic_Condensed-ExtraLight.ttf
          weight: 200
        - asset: assets/font/NotoSansArabic_Condensed-Light.ttf
          weight: 300
        - asset: assets/font/NotoSansArabic_Condensed-Regular.ttf
          weight: 400
        - asset: assets/font/NotoSansArabic_Condensed-Medium.ttf
          weight: 500
        - asset: assets/font/NotoSansArabic_Condensed-SemiBold.ttf
          weight: 600
        - asset: assets/font/NotoSansArabic_Condensed-Bold.ttf
          weight: 700
        - asset: assets/font/NotoSansArabic_Condensed-ExtraBold.ttf
          weight: 800
        - asset: assets/font/NotoSansArabic_Condensed-Black.ttf
          weight: 900
    - family: NotoSansArabicSemiCondensed
      fonts:
        - asset: assets/font/NotoSansArabic_SemiCondensed-Thin.ttf
          weight: 100
        - asset: assets/font/NotoSansArabic_SemiCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/font/NotoSansArabic_SemiCondensed-Light.ttf
          weight: 300
        - asset: assets/font/NotoSansArabic_SemiCondensed-Regular.ttf
          weight: 400
        - asset: assets/font/NotoSansArabic_SemiCondensed-Medium.ttf
          weight: 500
        - asset: assets/font/NotoSansArabic_SemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/font/NotoSansArabic_SemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/font/NotoSansArabic_SemiCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/font/NotoSansArabic_SemiCondensed-Black.ttf
          weight: 900
    - family: NotoSansArabicExtraCondensed
      fonts:
        - asset: assets/font/NotoSansArabic_ExtraCondensed-Thin.ttf
          weight: 100
        - asset: assets/font/NotoSansArabic_ExtraCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/font/NotoSansArabic_ExtraCondensed-Light.ttf
          weight: 300
        - asset: assets/font/NotoSansArabic_ExtraCondensed-Regular.ttf
          weight: 400
        - asset: assets/font/NotoSansArabic_ExtraCondensed-Medium.ttf
          weight: 500
        - asset: assets/font/NotoSansArabic_ExtraCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/font/NotoSansArabic_ExtraCondensed-Bold.ttf
          weight: 700
        - asset: assets/font/NotoSansArabic_ExtraCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/font/NotoSansArabic_ExtraCondensed-Black.ttf
          weight: 900

  assets:
    - assets/images/
    - assets/svg/
    - assets/font/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  branding: assets/images/logo.png
  color_dark: "#000000"
  image_dark: assets/images/logo.png
  branding_dark: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#000000"
  web: false
